name: CI

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BRIGHT_HOSTNAME: ${{ vars.BRIGHT_HOSTNAME }}
      APIURL: http://localhost:5000/api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: npm run create:env

      - name: Start server
        run: npm start &

      - name: Wait for server to be ready
        run: sleep 10

      - name: Run tests
        env:
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: npx tap test/sec/*.test.js